export { default as System} from './System'
export { default as Header} from './Header'
export { default as Sidebar} from './Sidebar'

export { default as CreatePost} from './CreatePost'
export { default as Admin} from './Admin/Admin'
export { default as SlideMenu} from './Admin/SlideMenu'
export { default as PageContent} from './Admin/PageContent'
export { default as Customers} from './Pages/Customers'
export { default as ManagePost} from './Pages/ManagePost'
export { default as ManageMenu} from './Pages/ManageMenu'