export { default as System} from './System'
export { default as Header} from './Header'
export { default as Sidebar} from './Sidebar'

export { default as Profile} from './Profile'
export { default as Order} from './Order'
export { default as Admin} from './Admin/Admin'
export { default as SlideMenu} from './Admin/SlideMenu'
export { default as PageContent} from './Admin/PageContent'
export { default as Customers} from './Pages/Customers'
export { default as ManagePost} from './Pages/ManagePost'
export { default as ManageMenu} from './Pages/ManageMenu'
export { default as ManageBooking} from './Pages/ManageBooking'
export { default as ManageTable} from './Pages/ManageTable'