const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGUOT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',


    GET_POSTS: "GET_POSTS",
    GET_NEW_POSTS: "GET_NEW_POSTS",
    GET_POSTSLIMIT: "GET_POSTSLIMIT",
    EDIT_POST: "EDIT_POST",

    // user
    GET_CURRENT: 'GET_CURRENT',
    GET_USER: "GET_USER",
    EDIT_USER: 'EDIT_USER',

    //menu
    GET_MENU: "GET_MENU",
    GET_MENU_LIMIT: "GET_MENU_LIMIT",
    EDIT_MENU: 'EDIT_MENU',

    // order
    GET_ORDER: 'GET_ORDER',

}

export default actionTypes